// Code generated by protoc-gen-go. DO NOT EDIT.
// source: evtlog.proto

package evtlog

import (
fmt "fmt"
proto "github.com/golang/protobuf/proto"
math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Evtlog struct {
Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
FileType string `protobuf:"bytes,2,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
Compressed bool `protobuf:"varint,3,opt,name=compressed,proto3" json:"compressed,omitempty"`
SeqNo uint64 `protobuf:"varint,4,opt,name=seq_no,json=seqNo,proto3" json:"seq_no,omitempty"`
FileName string `protobuf:"bytes,5,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
Size uint64 `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
File []byte `protobuf:"bytes,7,opt,name=file,proto3" json:"file,omitempty"`
ChunckTotal uint32 `protobuf:"varint,8,opt,name=chunck_total,json=chunckTotal,proto3" json:"chunck_total,omitempty"`
ChunckNo uint32 `protobuf:"varint,9,opt,name=chunck_no,json=chunckNo,proto3" json:"chunck_no,omitempty"`
XXX_NoUnkeyedLiteral struct{} `json:"-"`
XXX_unrecognized []byte `json:"-"`
XXX_sizecache int32 `json:"-"`
}

func (m *Evtlog) Reset() { *m = Evtlog{} }
func (m *Evtlog) String() string { return proto.CompactTextString(m) }
func (*Evtlog) ProtoMessage() {}
func (*Evtlog) Descriptor() ([]byte, []int) {
return fileDescriptor_9df2bbecfa77b681, []int{0}
}

func (m *Evtlog) XXX_Unmarshal(b []byte) error {
return xxx_messageInfo_Evtlog.Unmarshal(m, b)
}
func (m *Evtlog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
return xxx_messageInfo_Evtlog.Marshal(b, m, deterministic)
}
func (m *Evtlog) XXX_Merge(src proto.Message) {
xxx_messageInfo_Evtlog.Merge(m, src)
}
func (m *Evtlog) XXX_Size() int {
return xxx_messageInfo_Evtlog.Size(m)
}
func (m *Evtlog) XXX_DiscardUnknown() {
xxx_messageInfo_Evtlog.DiscardUnknown(m)
}

var xxx_messageInfo_Evtlog proto.InternalMessageInfo

func (m *Evtlog) GetVersion() string {
if m != nil {
return m.Version
}
return ""
}

func (m *Evtlog) GetFileType() string {
if m != nil {
return m.FileType
}
return ""
}

func (m *Evtlog) GetCompressed() bool {
if m != nil {
return m.Compressed
}
return false
}

func (m *Evtlog) GetSeqNo() uint64 {
if m != nil {
return m.SeqNo
}
return 0
}

func (m *Evtlog) GetFileName() string {
if m != nil {
return m.FileName
}
return ""
}

func (m *Evtlog) GetSize() uint64 {
if m != nil {
return m.Size
}
return 0
}

func (m *Evtlog) GetFile() []byte {
if m != nil {
return m.File
}
return nil
}

func (m *Evtlog) GetChunckTotal() uint32 {
if m != nil {
return m.ChunckTotal
}
return 0
}

func (m *Evtlog) GetChunckNo() uint32 {
if m != nil {
return m.ChunckNo
}
return 0
}

func init() {
proto.RegisterType((*Evtlog)(nil), "Evtlog")
}

func init() { proto.RegisterFile("evtlog.proto", fileDescriptor_9df2bbecfa77b681) }

var fileDescriptor_9df2bbecfa77b681 = []byte{
// 227 bytes of a gzipped FileDescriptorProto
0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x3f, 0x4b, 0xc4, 0x40,
0x10, 0xc5, 0x19, 0xcd, 0xe5, 0x92, 0xb9, 0xd8, 0x2c, 0x08, 0x03, 0x82, 0xac, 0x56, 0x5b, 0xd9,
0xf8, 0x0d, 0x04, 0xdb, 0x14, 0xcb, 0x55, 0x36, 0x21, 0xc6, 0x51, 0x83, 0xc9, 0x4e, 0x2e, 0xbb,
0x1e, 0x9c, 0x9f, 0x5c, 0xb0, 0x91, 0xdd, 0xf8, 0xe7, 0xba, 0x37, 0xbf, 0x37, 0xf3, 0x06, 0x1e,
0x56, 0xbc, 0x0f, 0x83, 0xbc, 0xdc, 0x4c, 0xb3, 0x04, 0xb9, 0xfe, 0x02, 0xcc, 0xef, 0x13, 0x50,
0x84, 0xeb, 0x3d, 0xcf, 0xbe, 0x17, 0x47, 0xa0, 0xc1, 0x94, 0xf6, 0x77, 0x54, 0x17, 0x58, 0x3e,
0xf7, 0x03, 0x37, 0xe1, 0x30, 0x31, 0x9d, 0x24, 0xaf, 0x88, 0x60, 0x7b, 0x98, 0x58, 0x5d, 0x22,
0x76, 0x32, 0x4e, 0x33, 0x7b, 0xcf, 0x4f, 0x74, 0xaa, 0xc1, 0x14, 0xf6, 0x88, 0xa8, 0x73, 0xcc,
0x3d, 0xef, 0x1a, 0x27, 0x94, 0x69, 0x30, 0x99, 0x5d, 0x79, 0xde, 0xd5, 0xf2, 0x97, 0xe9, 0xda,
0x91, 0x69, 0xf5, 0x9f, 0x59, 0xb7, 0x23, 0x2b, 0x85, 0x99, 0xef, 0x3f, 0x98, 0xf2, 0x74, 0x91,
0x74, 0x64, 0xd1, 0xa7, 0xb5, 0x06, 0x53, 0xd9, 0xa4, 0xd5, 0x15, 0x56, 0xdd, 0xeb, 0xbb, 0xeb,
0xde, 0x9a, 0x20, 0xa1, 0x1d, 0xa8, 0xd0, 0x60, 0xce, 0xec, 0x66, 0x61, 0xdb, 0x88, 0xe2, 0x9f,
0x9f, 0x15, 0x27, 0x54, 0x26, 0xbf, 0x58, 0x40, 0x2d, 0x77, 0x9b, 0x87, 0x7c, 0x69, 0xe3, 0x13,
0xe0, 0x31, 0x4f, 0x8d, 0xdc, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x3e, 0x7d, 0x71, 0x21,
0x01, 0x00, 0x00,
}
